blank_issues_enabled: true
contact_links:
  - name: Privater Team Tracker
    url: "https://github.com/Minebench/Internal/issues/new?assignees=&labels=bug&template=bug_report.md&title="
    about: Shortcut f√ºr Teammitglieder zum internen Tracker
  - name: Minebench Forum
    url: https://www.minebench.de/forum/
    about: Sensible Bugs bitte an ein Teammitglied im Forum oder ingame Privat schicken!
